### ISSUE TITLE
error not working

### ISSUE THREAD

**Issue by susantha1995** [voletro/TikTokToYT#12]
hi, after running main.py on the terminal it shows this error.
"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bots\tiktok\TikTokToYT\main.py", line 261, in <module>
    main()
  File "C:\Users\Administrator\Desktop\bots\tiktok\TikTokToYT\main.py", line 198, in main
    trending = api.by_trending(count=1, custom_verifyFp="")
  File "C:\Program Files\Python39\lib\site-packages\TikTokApi\tiktok.py", line 427, in by_trending
    if not res["hasMore"] and not first:
KeyError: 'hasMore'
"

why is that? please can you help me to fix this?

**Comment by h101-nazi** [comment]
i have th same error

**Comment by ethnyl** [comment]
any fix?

**Comment by mwall94** [comment]
Bumping this, getting the same error.

**Comment by elliotmarks06** [comment]
Anyone find a fix for this yet?
