### ISSUE TITLE
make it deployable on heroku & delete local video after upload to yt done

### ISSUE THREAD

**Issue by javazsaz** [voletro/TikTokToYT#2]
hi voletro,
at the first special thanks for your special work ,
please if it's possible make it deployable on heroku , all buildpacks needed like selenium are available & using set worker on procfile can run important command after heroku dyno awake daily & using http://kaffeine.herokuapp.com/ to ping every 30 minutes so it will never go to sleep :)
waiting for your commits for changes ;)
finest regards

**Comment by javazsaz** [comment]
hello again , 
after deployed to heroku using setting below get error :

████████╗██╗██╗  ██╗████████╗ ██████╗ ██╗  ██╗     ████████╗ ██████╗     ██╗   ██╗████████╗
╚══██╔══╝██║██║ ██╔╝╚══██╔══╝██╔═══██╗██║ ██╔╝     ╚══██╔══╝██╔═══██╗    ╚██╗ ██╔╝╚══██╔══╝
   ██║   ██║█████╔╝    ██║   ██║   ██║█████╔╝         ██║   ██║   ██║     ╚████╔╝    ██║   
   ██║   ██║██╔═██╗    ██║   ██║   ██║██╔═██╗         ██║   ██║   ██║      ╚██╔╝     ██║   
   ██║   ██║██║  ██╗   ██║   ╚██████╔╝██║  ██╗        ██║   ╚██████╔╝       ██║      ██║   
   ╚═╝   ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝        ╚═╝    ╚═════╝        ╚═╝      ╚═╝   

Traceback (most recent call last):
  File "/app/main.py", line 259, in <module>
    main()
  File "/app/main.py", line 196, in main
    api = TikTokApi.get_instance()
  File "/app/.heroku/python/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 149, in get_instance
    TikTokApi(**kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 59, in __init__
    self.browser = browser(**kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/TikTokApi/browser.py", line 82, in __init__
    raise e
  File "/app/.heroku/python/lib/python3.9/site-packages/TikTokApi/browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/app/.heroku/python/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 10094, in launch
    self._sync(
  File "/app/.heroku/python/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/app/.heroku/python/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    raise e
  File "/app/.heroku/python/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/app/.heroku/python/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/app/.heroku/python/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: ENOENT: no such file or directory, mkdtemp '/app/tmp/playwright-artifacts-N599ai'


my dyno setting is :

**Comment by voletro** [comment]
Hi javazsaz,
That's perfectly fine, I will start working on making it deployable on heroku now.
I will also quickly add support for removing the file after it is done uploading.
Thanks!

**Comment by shlomo-shlomo** [comment]
@voletro Is there anything new about it? Deployment using Harko would be a great thing !
