### ISSUE TITLE
Error when uploading video : AssertionError

### ISSUE THREAD

**Issue by BE-Zizoo** [voletro/TikTokToYT#4]
Can't upload to youtube : script is stopping with this error

Starting upload...
Traceback (most recent call last):
  File "main.py", line 261, in <module>
    main()
  File "main.py", line 236, in main
    assert "Channel dashboard" in driver.title
AssertionError

**Comment by Bartixxx32** [comment]
Same here

**Comment by Bartixxx32** [comment]
When i changed yt language to english error changed too ![Screenshot_20210821-215549.jpg](https://user-images.githubusercontent.com/16412925/130333443-5477706e-bfb3-4e03-987d-f739d793098b.jpg)

**Comment by voletro** [comment]
This is due to a prompt that appears when accessing YouTube studio at the moment, saying that there is a new dark mode available. Simply go onto YouTube Studio in Firefox and close the prompt.

**Comment by BE-Zizoo** [comment]
No, sorry.. thats not the problem. The prompt is closed and does not come back. But i keep getting the same error


Starting upload...
Traceback (most recent call last):
File "main.py", line 261, in
main()
File "main.py", line 236, in main
assert "Channel dashboard" in driver.title
AssertionError

**Comment by Bartixxx32** [comment]
It could be hard ond headless mode to close prompt, better soluyion would be if you will add in code auto clicking on prompt to accept i guess

**Comment by Bartixxx32** [comment]
@BE-Zizoo make sure to set the youtube language to english becouse if you have other lang this error happens, i changed to english and got other error as above

**Comment by Bartixxx32** [comment]
Maybe better will be to switch the project from selenium to some kind of youtube uploader api?
Like this: https://github.com/tokland/youtube-upload

**Comment by Bartixxx32** [comment]
Im now stuck with message about verifying

**Comment by bilalz666** [comment]
> Im now stuck with message about verifying

just login youtube in same device or ip. then, get cookies from there.
