### ISSUE TITLE
TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by cnbgfm** [voletro/TikTokToYT#9]
Traceback (most recent call last):
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000229BF7E1640>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.tiktok.com', port=443): Max retries exceeded with url: /api/recommend/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F15.4%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=728&screen_height=330&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=1&id=1&secUid=&sourceType=12&appId=1233&itemID=1&insertedItemID=&region=US&priority_region=US&language=en&verifyFp=&did=0003817803616257953&_signature=_02B4Z6wo00f01vXQZDwAAIBC.yHcUMK13sr1wWCAAN0Hb2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000229BF7E1640>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TikTokToYT\main.py", line 261, in <module>
    main()
  File "D:\TikTokToYT\main.py", line 198, in main
    trending = api.by_trending(count=1, custom_verifyFp="")
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 423, in by_trending
    res = self.get_data(url=api_url, **kwargs)
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 242, in get_data
    h = requests.head(
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 102, in head
    return request('head', url, **kwargs)
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mawanyan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.tiktok.com', port=443): Max retries exceeded with url: /api/recommend/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F15.4%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=728&screen_height=330&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=1&id=1&secUid=&sourceType=12&appId=1233&itemID=1&insertedItemID=&region=US&priority_region=US&language=en&verifyFp=&did=0003817803616257953&_signature=_02B4Z6wo00f01vXQZDwAAIBC.yHcUMK13sr1wWCAAN0Hb2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000229BF7E1640>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反 应，连接尝试失败。'))

**Comment by cnbgfm** [comment]
In urllib3 version 1.25.11 working perfectly. So you can install urllib3 1.25.11 by following command line.
`pip install urllib3==1.25.11`
